# Generated by Django 4.1 on 2022-10-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('latitude_north', models.FloatField(default=0)),
                ('latitude_south', models.FloatField(default=0)),
                ('longitude_east', models.FloatField(default=0)),
                ('longitude_west', models.FloatField(default=0)),
                ('mushroom_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
