# Generated by Django 4.1 on 2022-11-02 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('latitude_north', models.FloatField(default=0)),
                ('latitude_south', models.FloatField(default=0)),
                ('longitude_east', models.FloatField(default=0)),
                ('longitude_west', models.FloatField(default=0)),
                ('mushroom_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=55)),
                ('image', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
