# Generated by Django 4.1 on 2022-10-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='longitute_east',
            new_name='longitude_east',
        ),
        migrations.RenameField(
            model_name='mushroom',
            old_name='longitute_west',
            new_name='longitude_west',
        ),
    ]
