# Generated by Django 4.1 on 2022-10-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_app', '0002_rename_longitute_east_mushroom_longitude_east_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='image',
            field=models.URLField(),
        ),
    ]
